# Generated by Django 4.1.7 on 2023-03-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant_review", "0002_alter_review_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("message_body", models.TextField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
