# Generated by Django 4.1.7 on 2023-03-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant_review", "0003_sms"),
    ]

    operations = [
        migrations.AddField(
            model_name="sms",
            name="twilio_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
