# Generated by Django 4.1.7 on 2023-03-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "restaurant_review",
            "0005_remove_sms_message_body_remove_sms_sent_at_message",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sms",
            name="message_body",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
