# Generated by Django 4.1.7 on 2023-03-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant_review", "0008_post_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="WelcomeGreeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
            ],
        ),
    ]
